spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: admin_rote
          uri: lb://admin
          predicates:
            - Path=/admin/**

        - id: course_rote
          uri: lb://course
          predicates:
            - Path=/course/**
server:
  port: 8082